name: app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.10
  http: ^1.2.2
  mysql1: ^0.20.0
  table_calendar: ^3.1.2
  vm_service: ^14.2.4
  fluttertoast: ^8.2.8
  sqflite: ^2.4.0
  path: ^1.9.0
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  logging: ^1.3.0
  cloud_firestore: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
